### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by flip111**

### CODE REVIEW

**Comment by flip111** [comment]
Binary has `llvm-config` but is missing `llvm-sys`.

**Comment by flip111** [comment]
i'm closing this until the entire flow for windows works .. right now there are other problems

**Comment by flip111** [comment]
What i'm gonna put in the readme so far is:

```
### Windows installation with Visual Studio

1. Get Visual Studio or the Microsoft Visual C++ build tools as described on the rust-lang downloads [foot note](https://www.rust-lang.org/downloads.html#win-foot)
2. Download a windows binary of llvm at https://i10z.com/llvm/win64/
3. Get rust 64-bits with msvc abi from the [rust download page](https://www.rust-lang.org/downloads.html) or use https://www.rustup.rs/ (recommended). When using rustup run `rustup default stable-x86_64-msvc` to install the 64-bits version
4. Start the 64-bits compiler environment. It's probably in your start menu called "VS2015 x64 Native Tools Command Prompt".
5. cargo build --release

Note: there are no 32-bits installation instructions because it's unclear where to download a 32-bits llvm binary for windows.
```

Right now there is still a build problem which is being tracked here https://bitbucket.org/tari/llvm-sys.rs/issues/9/include-path-for-llvm-headers-on-windows

**Comment by Hywan** [comment]
You might be interesting by https://bitbucket.org/tari/llvm-sys.rs/issues/6/build-on-windows. I tried with AppVeyor at the beginning and got some troubles.

**Pull request closed without merging**
