### PR TITLE
Docker dev image

### PR DESCRIPTION
**Pull request by mathroc**
continuing tagua-vm/tagua-vm#15

update Dockerfile so it builds again

upgrade to Rust 1.9
uses LLVM 3.6
smaller image: 1.114 GB -> 791.2 MB

cargo test, doc & build are working but I don't know how to execute a simple php file (maybe it does not works yet)

> root@03eff5d2c4ee:/source# RUST_BACKTRACE=1 target/debug/tvm <(echo '<?php echo "Hello world!";')
> thread '<main>' panicked at 'Youhouuu', source/language/parser/rules/mod.rs:45
> stack backtrace:
>    1:     0x55e9278773a0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
>    2:     0x55e927879dbb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
>    3:     0x55e927879a43 - std::panicking::default_hook::haac48fa641db8fa2
>    4:     0x55e9278701af - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
>    5:     0x55e92779c317 - std::sys_common::unwind::begin_unwind::hd78480d5ec5c51b2
>                         at ../src/libstd/sys/common/unwind/mod.rs:219
>    6:     0x55e92779b1f9 - tagua_vm::language::parser::rules::root::hca07418bb36f8275
>                         at /source/<std macros>:3
>    7:     0x55e92779b173 - tagua_vm::language::parser::parse::h13da034f0798fbfe
>                         at source/language/parser/mod.rs:66
>    8:     0x55e927794161 - tvm::file::h329528a6841c612a
>                         at source/bin/tvm.rs:71
>    9:     0x55e927795a7f - tvm::process_options::hd4ee102c54a59663
>                         at source/bin/tvm.rs:145
>   10:     0x55e9277973dd - tvm::main::h33bc5794f22b1834
>                         at source/bin/tvm.rs:155
>   11:     0x55e927879684 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
>   12:     0x55e92787680b - __rust_try
>   13:     0x55e9278790cb - std::rt::lang_start::h5b0863080165c75e
>   14:     0x55e9277993c9 - main
>   15:     0x7f2e3e10d5ef - __libc_start_main
>   16:     0x55e927793bb8 - _start
>   17:                0x0 - <unknown>

also added a Dockerfile for a tvm container. can be run like that:

``` sh
echo '<?php echo date("c"), PHP_EOL;' > date.php
docker-compose run -e RUST_BACKTRACE=1 --rm tvm date.php
```

### CODE REVIEW

**Comment by Hywan** [comment]
Yup, running a PHP file does not work yet. Only additions are supporter yet, like `1+2`, only that (no `<?php` etc.) Parser is growing.

**Comment by mathroc** [comment]
oh alright!

that's working:

``` sh
echo '1+2;' > add.php
docker-compose run --rm tvm add.php
```

> THE result is 3.

**Comment by Hywan** [comment]
@mathroc #15 has been merged so I assume you can rebase your PR now :-).

**Comment by mathroc** [comment]
see #65 for starters

**Pull request closed without merging**
